version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commans: 
      - echo DO-SOMETHING PRE BUILD PHASE

  build: 
    commands:
      - echo DO-SOMETHING
  
  post_build: 
    commands:
      - echo DO-SOMETHING AFTER BUILD PHASE

artifacts:
  files:
    - template/*